[package]
name = "solarhorizon/react-rodux"
description = "A simple bridge between React and Rodux"
authors = ["SolarHorizon"]
version = "0.2.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json"]

[dependencies]
React = "jsdotlua/react@17.0.1"
Rodux = "roblox/rodux@4.0.0-rc.0"
LuauPolyfill = "jsdotlua/luau-polyfill@1.2.3"
